version: '3.2'

services:
  proxy:
    image: traefik:v2.1.1
    hostname: proxy
    domainname: srvz-webapp.he-arc.ch
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/etc/traefik/traefik.toml
      - proxy:/etc/traefik/acme
    ports:
      - "8080:8080"
      - "80:80"
      - "443:443"
    command: -c /etc/traefik/traefik.toml --docker.domain=localhost --api.debug

  portainer:
    image: portainer/portainer:1.23.0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer:/data
    # private
    ports:
      - "9000:9000"
    # public
    #labels:
    #  - "traefik.enable=true"
    #  - "traefik.http.routers.portainer.rule=Host(`portainer.srvz-webapp.he-arc.ch`)"
    #  - "traefik.http.services.portainer.loadbalancer.server.port=9000"

  # Databases

  postgres:
    image: postgres:10-alpine
    container_name: postgres
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
     - postgres:/var/lib/postgresql/data

  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"
    volumes:
      - mysql:/var/lib/mysql

  # Email

  smtp:
    image: mailhog/mailhog:latest
    container_name: smtp
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.smtp.rule=Host(`webmail.srvz-webapp.he-arc.ch`)"
      - "traefik.http.services.smtp-service.loadbalancer.server.port=8025"

networks:
  default:
    external:
      name: webapp-net

volumes:
  proxy:
  portainer:
  mysql:
  postgres:
