version: '2'

services:
   # Free project
  free:
    image: greut/webapp-server:latest
    environment:
      - GROUPNAME=free
      - PASSWORD=root
      - REPOSITORY=http://github.com/HE-Arc/demo-rails-application
    hostname: free
    domainname: srvz-webapp.he-arc.ch
    volumes:
      - free:/var/www
      - ./config:/root/config:ro
    ports:
      - "2222:22"
      - "8080:80"
    depends_on:
      - postgres
      - mysql
      - smtp
    networks:
      - free
    mem_limit: 1000000000
    memswap_limit: 2000000000

  # Python

  python:
    image: greut/webapp-server:python
    environment:
      - GROUPNAME=free
      - PASSWORD=root
      - REPOSITORY=http://github.com/HE-Arc/demo-rails-application
    hostname: python
    domainname: srvz-webapp.he-arc.ch
    volumes:
      - python:/var/www
      - ./config:/root/config:ro
    ports:
      - "2222:22"
      - "8080:80"
    depends_on:
      - postgres
      - mysql
      - smtp
    networks:
      - python
    mem_limit: 1000000000
    memswap_limit: 2000000000


  # PHP project.

  eatapp:
    image: greut/webapp-server:laravel
    environment:
      - GROUPNAME=eatapp
      - PASSWORD=eatapp  # CHANGE ME
      - REPOSITORY=https://github.com/HE-Arc/EatApp
    hostname: eatapp
    domainname: srvz-webapp.he-arc.ch
    volumes:
      - eatapp:/var/www
      - ./config:/root/config:ro
    ports:
      - "2222:22"
      - "8080:80"
    depends_on:
      - postgres
      - mysql
      - smtp
    links:
      - eatapp_redis:redis
    networks:
      - eatapp
    mem_limit: 1000000000
    memswap_limit: 2000000000

  eatapp_redis:
    image: redis:3.2-alpine
    networks:
      - eatapp
    volumes:
      - eatapp_redis:/data

  # Ruby on Rails project

  capistrano:
    image: greut/webapp-server:rails
    environment:
      - GROUPNAME=capistrano
      - PASSWORD=capistrano  # CHANGE ME
    hostname: capistrano
    domainname: srvz-webapp.he-arc.ch
    volumes:
      - capistrano:/var/www
      - ./config:/root/config:ro
    ports:
      - "2020:22"
      - "8080:80"
    depends_on:
      - postgres
      - mysql
      - smtp
    links:
      - capistrano_redis:redis
    networks:
      - capistrano
    mem_limit: 1000000000
    memswap_limit: 2000000000

  capistrano_redis:
    image: redis:3.2-alpine
    networks:
      - capistrano
    volumes:
      - capistrano_redis:/data

  # Shared services
  postgres:
    image: postgres:9.5
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    networks:
      - capistrano
      - eatapp
      - free
      - python
    volumes:
     - postgres:/var/lib/postgresql/data

  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"
    networks:
      - capistrano
      - eatapp
      - free
      - python
    volumes:
      - mysql:/var/lib/mysql

  smtp:
    image: mailhog/mailhog:latest
    ports:
      - "8025:8025"
    networks:
      - free
      - eatapp
      - capistrano

networks:
  # base
  free:
  # laravel
  eatapp:
  # python
  python:
  # rails
  capistrano:

volumes:
  mysql:
  postgres:
  # base
  free:
  # laravel
  eatapp:
  eatapp_redis:
  # python
  python:
  # rails
  capistrano:
  capistrano_redis:
