version: '2'

services:

  # Build only!
  base:
    image: greut/webapp-server:latest
    build:
      dockerfile: docker/base
      context: .

  laravel:
    image: greut/webapp-server:laravel
    build:
      dockerfile: docker/laravel
      context: .

  rails:
    image: greut/webapp-server:rails
    build:
      dockerfile: docker/rails
      context: .

  # PHP project.

  eatapp:
    image: greut/webapp-server:laravel
    environment:
      - GROUPNAME=eatapp
      - MYSQL_USERNAME=eatapp
      - MYSQL_PASSWORD=eatapp  # CHANGE ME
      - POSTGRES_USERNAME=eatapp
      - POSTGRES_PASSWORD=eatapp  # ME TOO
      - REPOSITORY=https://github.com/HE-Arc/EatApp
    hostname: eatapp
    domainname: srvz-webapp.he-arc.ch
    volumes:
      - eatapp:/var/www
      - ./config:/root/config:ro
    ports:
      - "2222:22"
      - "8888:80"
    depends_on:
      - postgres
      - mysql
      - smtp
    links:
      - eatapp_redis:redis
    networks:
      - eatapp
    mem_limit: 1000000000
    memswap_limit: 2000000000

  eatapp_redis:
    image: redis:3.2-alpine
    networks:
      - eatapp
    volumes:
      - eatapp_redis:/data

  # Ruby on Rails project

  capistrano:
    image: greut/webapp-server:rails
    environment:
      - GROUPNAME=capistrano
      - MYSQL_USERNAME=capistrano
      - MYSQL_PASSWORD=capistrano  # CHANGE ME
      - POSTGRES_USERNAME=capistrano
      - POSTGRES_PASSWORD=capistrano  # ME TOO
    hostname: capistrano
    domainname: srvz-webapp.he-arc.ch
    volumes:
      - capistrano:/var/www
      - ./config:/root/config:ro
    ports:
      - "2020:22"
      - "8080:80"
    depends_on:
      - postgres
      - mysql
      - smtp
    links:
      - capistrano_redis:redis
    networks:
      - capistrano
    mem_limit: 1000000000
    memswap_limit: 2000000000

  capistrano_redis:
    image: redis:3.2-alpine
    networks:
      - capistrano
    volumes:
      - capistrano_redis:/data

  # Shared services
  postgres:
    image: postgres:9.5
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    networks:
      - eatapp
      - capistrano
    volumes:
     - postgres:/var/lib/postgresql/data

  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"
    networks:
      - eatapp
      - capistrano
    volumes:
      - mysql:/var/lib/mysql

  smtp:
    image: mailhog/mailhog:latest
    ports:
      - "8025:8025"
    networks:
      - eatapp
      - capistrano

networks:
  # laravel
  eatapp:
  # rails
  capistrano:

volumes:
  mysql:
  postgres:
  # laravel
  eatapp:
  eatapp_redis:
  # rails
  capistrano:
  capistrano_redis:
