version: '3.2'

services:
  proxy:
    image: traefik:1.3-alpine
    hostname: proxy
    domainname: docker.localhost
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/etc/traefik/traefik.toml
      - proxy:/etc/traefik/acme
    ports:
      - "8080"
      - "80"
      - "443"
    command: -c /etc/traefik/traefik.toml --docker.domain=docker.localhost
    labels:
      - "traefik.enable=false"

  portainer:
    image: portainer/portainer
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer:/data
    ports:
      - "9000"
    #labels:
    #  - "traefik.backend=portainer"
    #  - "traefik.frontend.rule=PathPrefixStrip:/portainer"
    #  - "traefik.port=9000"

  # Databases

  postgres:
    image: postgres:9.6-alpine
    container_name: postgres
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "5432"
    volumes:
     - postgres:/var/lib/postgresql/data
    labels:
      - "traefik.enable=false"

  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306"
    volumes:
      - mysql:/var/lib/mysql
    labels:
      - "traefik.enable=false"

  # Email

  smtp:
    image: mailhog/mailhog:latest
    container_name: smtp
    labels:
      - "traefik.frontend.rule=Host:webmail.docker.localhost"
      - "traefik.port=8025"

networks:
  default:
    external:
      name: webapp-net

volumes:
  proxy:
  portainer:
  mysql:
  postgres:
