version: '2'

services:
  greut:
    image: greut/webapp-server:rails
    environment:
      - GROUPNAME=yoan_blanc
      - PASSWORD=root
      - LONE_WOLF="true"
    hostname: yoan.blanc
    domainname: srvz-webapp.he-arc.ch
    volumes:
      - greut:/var/www
      - ./config:/root/config:ro
    ports:
      - "2020:22"
      - "8080:80"
      - "8888:8888" # iruby (jupyter)
    depends_on:
      - postgres
      - mysql
      - smtp

    links:
      - greut_redis:redis

  greut_redis:
    image: redis:3.2-alpine

  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"
    volumes:
      - mysql:/var/lib/mysql

  postgres:
    image: postgres:9.6-alpine
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
     - postgres:/var/lib/postgresql/data

  smtp:
    image: mailhog/mailhog:latest
    ports:
      - "8025:8025"

volumes:
  postgres:
  mysql:
  # users
  greut:
