[log]
  level = "DEBUG"
  filePath = "/proc/self/fd/1"
  format = "json"

[api]
  dashboard = true
  insecure = true

[providers.docker]
  endpoint = "unix:///var/run/docker.sock"
  watch = true
  exposedByDefault = true

[entryPoints.web]
  address = ":80"

[entryPoints.traefik]
  address = ":8080"

[http.routers]
  [http.routers.api]
    service="api@internal"

  [http.routers.web]
    entrypoints = ["web"]
    middlewares = ["redirect"]

  [http.routers.web-secure]
    entrypoints = ["traefik"]
    [http.routers.web-secure.tls]

[http.middlewares]
  [http.middlewares.redirect.redirectScheme]
    scheme = "https"

[certificatesResolvers.sample.acme]
  email = "yoan.blanc@he-arc.ch"
  storage = "acme.json"
  [certificatesResolvers.sample.acme.httpChallenge]
    entryPoint = "web"