#debug = true
logLevel = "INFO"
defaultEntryPoints = ["http", "https"]

traefikLogsFile = "/proc/self/fd/1"
accessLogsFile = "/proc/self/fd/1"

[api]
  dashboard = true

[web]
  address = ":8080"

[providers.docker]
  endpoint = "unix:///var/run/docker.sock"
  watch = true
  exposedByDefault = true

[entryPoints]
  [entryPoints.http]
  address =":80"
  [entryPoints.https]
  address = ":443"

[certificatesResolvers.sample.acme]
  email = "yoan.blanc@he-arc.ch"
  storage = "acme.json"

# Use a HTTP-01 acme challenge rather than TLS-SNI-01 challenge
  [acme.httpChallenge]
    entryPoint = "https"