#debug = true
logLevel = "INFO"
defaultEntryPoints = ["http", "https"]

traefikLogsFile = "/proc/self/fd/1"
accessLogsFile = "/proc/self/fd/1"

[web]
address = ":8080"

[docker]
endpoint = "unix:///var/run/docker.sock"
watch = true
exposedbydefault = false

[acme]
email = "yoan.blanc@he-arc.ch"
storage = "/etc/traefik/acme/acme.json"
acmeLogging = true
onDemand = true
onHostRule = true
entryPoint = "https"

[entryPoints]
  [entryPoints.http]
  address =":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]
