version: '3.2'

services:
  weblog:
    image: hearcch/webapp-server:python
    environment:
      - GROUPNAME=weblog
      - PASSWORD=root
      - SSH_KEYS=greut grunenwald
    hostname: python
    volumes:
      - weblog:/var/www
    ports:
      - "2223:22"
    external_links:
      - postgres
      - mysql
      - smtp
    labels:
      - "traefik.http.routers.web.rule=Host(`weblog.srvz-webapp.he-arc.ch`)"

  weblog_redis:
    image: redis:5-alpine
    volumes:
      - weblog_redis:/data

networks:
  default:
    external:
      name: webapp-net

volumes:
  weblog:
  weblog_redis:
